"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.COLOR_BLUE = exports.COLOR_RED = exports.COLOR_ORANGE_GLOW = exports.COLOR_WHITE = exports.COLOR_GRAY_ACCENT = exports.COLOR_GRAY = exports.COLOR_LIGHT_GRAY = exports.COLOR_DARK_GRAY = exports.COLOR_NEAR_BLACK = exports.COLOR_BLACK = exports.COLOR_TOKEN_DARK = exports.COLOR_TOKEN_SLATE = exports.COLOR_TOKEN_PINK = exports.COLOR_TOKEN_PURPLE = exports.COLOR_TOKEN_BLUE = exports.COLOR_TOKEN_CYAN = exports.COLOR_TOKEN_GREEN = exports.COLOR_TOKEN_YELLOW = exports.COLOR_TOKEN_ORANGE = exports.COLOR_TOKEN_RED = exports.PAINT_DURATION = exports.COLOR_LERP_TIME = exports.ROTATION_SPEED = exports.ACCEL_TIME = exports.MAX_BOOST = exports.GRID_MAJOR = exports.GRID_MINOR = exports.POINT_SPACING = exports.GRID_SIZE = exports.CANVAS_H = exports.CANVAS_W = exports.GAME_FONT = void 0;
exports.GAME_FONT = "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";
exports.CANVAS_W = 405;
exports.CANVAS_H = 720;
exports.GRID_SIZE = 20;
exports.POINT_SPACING = 0.5;
exports.GRID_MINOR = 20;
exports.GRID_MAJOR = 100;
exports.MAX_BOOST = 300;
exports.ACCEL_TIME = 0.5;
exports.ROTATION_SPEED = Math.PI * 4;
exports.COLOR_LERP_TIME = 0.4;
exports.PAINT_DURATION = 1.5;
exports.COLOR_TOKEN_RED = "#e53935";
exports.COLOR_TOKEN_ORANGE = "#fb8c00";
exports.COLOR_TOKEN_YELLOW = "#f9ab00";
exports.COLOR_TOKEN_GREEN = "#43a047";
exports.COLOR_TOKEN_CYAN = "#00acc1";
exports.COLOR_TOKEN_BLUE = "#1a73e8";
exports.COLOR_TOKEN_PURPLE = "#8e24aa";
exports.COLOR_TOKEN_PINK = "#e91e63";
exports.COLOR_TOKEN_SLATE = "#546e7a";
exports.COLOR_TOKEN_DARK = "#222222";
exports.COLOR_BLACK = "#000";
exports.COLOR_NEAR_BLACK = "#111";
exports.COLOR_DARK_GRAY = "#333";
exports.COLOR_LIGHT_GRAY = "#bbb";
exports.COLOR_GRAY = "#ccc";
exports.COLOR_GRAY_ACCENT = "#999";
exports.COLOR_WHITE = "#fff";
exports.COLOR_ORANGE_GLOW = "rgba(255,140,0,0.8)";
exports.COLOR_RED = exports.COLOR_TOKEN_RED;
exports.COLOR_BLUE = exports.COLOR_TOKEN_BLUE;
