/* eslint-disable @typescript-eslint/no-explicit-any */
export const circle: any = 'circle'
export const clipPath: any = 'clipPath'
export const defs: any = 'defs'
export const feColorMatrix: any = 'feColorMatrix'
export const feGaussianBlur: any = 'feGaussianBlur'
export const filter: any = 'filter'
export const g: any = 'g'
export const line: any = 'line'
export const mask: any = 'mask'
export const path: any = 'path'
export const polygon: any = 'polygon'
export const rect: any = 'rect'
export const text: any = 'text'
