"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.text = exports.rect = exports.polygon = exports.path = exports.mask = exports.line = exports.g = exports.filter = exports.feGaussianBlur = exports.feColorMatrix = exports.defs = exports.clipPath = exports.circle = void 0;
var react_native_svg_1 = require("react-native-svg");
Object.defineProperty(exports, "circle", { enumerable: true, get: function () { return react_native_svg_1.Circle; } });
Object.defineProperty(exports, "clipPath", { enumerable: true, get: function () { return react_native_svg_1.ClipPath; } });
Object.defineProperty(exports, "defs", { enumerable: true, get: function () { return react_native_svg_1.Defs; } });
Object.defineProperty(exports, "feColorMatrix", { enumerable: true, get: function () { return react_native_svg_1.FeColorMatrix; } });
Object.defineProperty(exports, "feGaussianBlur", { enumerable: true, get: function () { return react_native_svg_1.FeGaussianBlur; } });
Object.defineProperty(exports, "filter", { enumerable: true, get: function () { return react_native_svg_1.Filter; } });
Object.defineProperty(exports, "g", { enumerable: true, get: function () { return react_native_svg_1.G; } });
Object.defineProperty(exports, "line", { enumerable: true, get: function () { return react_native_svg_1.Line; } });
Object.defineProperty(exports, "mask", { enumerable: true, get: function () { return react_native_svg_1.Mask; } });
Object.defineProperty(exports, "path", { enumerable: true, get: function () { return react_native_svg_1.Path; } });
Object.defineProperty(exports, "polygon", { enumerable: true, get: function () { return react_native_svg_1.Polygon; } });
Object.defineProperty(exports, "rect", { enumerable: true, get: function () { return react_native_svg_1.Rect; } });
Object.defineProperty(exports, "text", { enumerable: true, get: function () { return react_native_svg_1.Text; } });
